SMARTCOUNT_LOGO_PATH: assets\logo_smartcount.jpeg
FRAME_NAME: Video Feed
OUTPUT_VIDEO_PATH: output.mp4
TERM_CRITERIA: [3, 10, 1]
FRAMES_TO_SKIP: 2
DISPLAY_WINDOW: false

OBJECTS:
  - NAME: MP_1
    DATASET_FOLDER: datasets\MP_1
    MIN_AREA: 600
    MAX_AREA: 1000
    CLIP_WIDTH: 108
    CLIP_HEIGHT: 62
    ALLOWED_IOU: 0.1
    DETECTION_THRESHOLD: 0.95
    TF_MODEL_PATH: models\model_v4.h5
    TF_MODEL_COLOR: RGB
    CLIP_STRATEGY: ANCHOR_POINTS
    CONVEYOR_DIRECTION: RIGHT
    CONVEYOR_SPEED: 2
    
    HAS_CAPTURE_FRAME: true
    CAPTURE_FRAME_X: 100
    CAPTURE_FRAME_Y: 0
    CAPTURE_FRAME_WIDTH: 300
    CAPTURE_FRAME_HEIGHT: 900


