SMARTCOUNT_LOGO_PATH: assets\logo_smartcount.jpeg
FRAME_NAME: Video Feed
OUTPUT_VIDEO_PATH: output.mp4
TERM_CRITERIA: [3, 10, 1]
FRAMES_TO_SKIP: 1
DISPLAY_WINDOW: false

OBJECTS:
  - NAME: CLIPS_1
    DATASET_FOLDER: datasets\CLIPS_1
    MIN_AREA: 100
    MAX_AREA: 500
    CLIP_WIDTH: 76
    CLIP_HEIGHT: 76
    ALLOWED_IOU: 0.1
    DETECTION_THRESHOLD: 0.9
    TF_MODEL_PATH: models\model_clips_v1.h5

    CLIP_STRATEGY: NONE
    CONVEYOR_DIRECTION: DIAG
    CONVEYOR_SPEED: 25

    HAS_CAPTURE_FRAME: true
    CAPTURE_FRAME_X: 200
    CAPTURE_FRAME_Y: 100
    CAPTURE_FRAME_WIDTH: 350
    CAPTURE_FRAME_HEIGHT: 300

