SMARTCOUNT_LOGO_PATH: assets\logo_smartcount.jpeg
FRAME_NAME: Video Feed
OUTPUT_VIDEO_PATH: output.mp4
TERM_CRITERIA: [3, 10, 1]
FRAMES_TO_SKIP: 1
DISPLAY_WINDOW: true

OBJECTS:
  - NAME: ROAD_1
    DATASET_FOLDER: datasets\ROAD_1
    MIN_AREA: 2000
    MAX_AREA: 10000
    CLIP_WIDTH: 146
    CLIP_HEIGHT: 146
    ALLOWED_IOU: 0.1
    DETECTION_THRESHOLD: 0.90
    TF_MODEL_PATH: models\model_road_1_v1.h5
    TF_MODEL_COLOR: RGB
    CLIP_STRATEGY: NONE
    CONVEYOR_DIRECTION: NONE
    HAS_CAPTURE_FRAME: true
    CAPTURE_FRAME_X: 0
    CAPTURE_FRAME_Y: 300
    CAPTURE_FRAME_WIDTH: 1400
    CAPTURE_FRAME_HEIGHT: 400
 

