SMARTCOUNT_LOGO_PATH: assets\logo_smartcount.jpeg
FRAME_NAME: Video Feed
OUTPUT_VIDEO_PATH: output.mp4
TERM_CRITERIA: [3, 10, 1]
FRAMES_TO_SKIP: 2

OBJECTS:
  - NAME: TK_1
    DATASET_FOLDER: datasets\TK_1
    MIN_AREA: 3000
    MAX_AREA: 4000
    CLIP_WIDTH: 116
    CLIP_HEIGHT: 116
    CONVEYOR_DIRECTION: DOWN
    CONVEYOR_SPEED: 15
    DETECTION_THRESHOLD: 0.85
    TF_MODEL_PATH: models\model_tk_v1.h5

