SMARTCOUNT_LOGO_PATH: assets\logo_smartcount.jpeg
FRAME_NAME: Video Feed
OUTPUT_VIDEO_PATH: output.mp4
TERM_CRITERIA: [3, 10, 1]
FRAMES_TO_SKIP: 1
DISPLAY_WINDOW: false

OBJECTS:
  - NAME: WEBCAM_1
    DATASET_FOLDER: datasets\WEBCAM_1
    MIN_AREA: 10
    MAX_AREA: 300
    CLIP_WIDTH: 76
    CLIP_HEIGHT: 76
    ALLOWED_IOU: 0.0
    DETECTION_THRESHOLD: 0.95
    TF_MODEL_PATH: models\model_webcam_1_v1.h5
    TF_MODEL_COLOR: RGB
    CLIP_STRATEGY: NONE
    CONVEYOR_DIRECTION: NONE   
    HAS_CAPTURE_FRAME: false
 

